### ISSUE TITLE
Error: argument message length cannot be zero

### ISSUE THREAD

**Issue by pfrazee** [dominictarr/pull-box-stream#7]
I've been running into a crash error.

```
in { req: 2,
  stream: false,
  end: false,
  value: { name: [ 'usage' ], args: [ 'feed' ] },
  length: 34,
  type: 2 }
out { value: '', end: false, req: -2 }
/Users/paulfrazee/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-box-stream/index.js:14
  return sodium.crypto_secretbox_easy(buffer, nonce, key)
                ^
Error: argument message length cannot be zero
    at Error (native)
    at box (/Users/paulfrazee/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-box-stream/index.js:14:17)
    at Object.<anonymous> (/Users/paulfrazee/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-box-stream/index.js:75:19)
    at /Users/paulfrazee/scuttlebot/node_modules/secret-stack/node_modules/secret-handshake/node_modules/pull-box-stream/node_modules/pull-through/index.js:56:20
    at /Users/paulfrazee/scuttlebot/node_modules/pull-abortable/index.js:38:11
    at /Users/paulfrazee/scuttlebot/node_modules/pull-stream/throughs.js:126:7
    at pull (/Users/paulfrazee/scuttlebot/node_modules/packet-stream-codec/node_modules/pull-through/index.js:46:20)
    at next (/Users/paulfrazee/scuttlebot/node_modules/packet-stream-codec/node_modules/pull-through/node_modules/looper/index.js:7:11)
    at module.exports (/Users/paulfrazee/scuttlebot/node_modules/packet-stream-codec/node_modules/pull-through/node_modules/looper/index.js:13:5)
    at /Users/paulfrazee/scuttlebot/node_modules/pack
```

It looks like the `usage()` call is responding with an empty string, and that's causing pull-box-stream to freak out (because it's an empty response). Seems like we need to support empty responses.

**Comment by dominictarr** [comment]
hmm, how did you make that? I think that may be a problem with sodium... what do i need to do to reproduce this error?

**Comment by pfrazee** [comment]
Easy way to reproduce: check out the `cli-validated` branch of scuttlebot, start the server, then run `./bin.js log -h`. I havent implemented usage output for command-aliases yet, so the `usage()` function returns an empty string. That triggers this error.

**Comment by dominictarr** [comment]
okay I figured this one out. that is actually a sodium error. well, it's a sodium behavior (refuses to encrypt zero length buffers) combined with a packet-stream-codec behaviour (sends writes header (length, type) then body (buffer) of each packet without concatenating them).

I can fix this by just having pull-box-stream dropping any zero length packets.

pull-box-stream is not responsible for perserving packet lengths (and it has a max length) so users must  a framing protocol if packets have significant boundries.

**Comment by dominictarr** [comment]
fixed in 1.0.7

**Comment by dominictarr** [comment]
reinstall to get latest patch in secret-handshake, then you should be good.

**Comment by pfrazee** [comment]
:+1: server no longer crashes
